services:
  notification_service:
    build: .
    container_name: notification_service
    ports:
      - "8003:8003"
    restart: always
    env_file:
      - .env
    command: npx tsx watch app/app/server.ts
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - shoponbot_external_shared_net

networks:
  shoponbot_external_shared_net:
    external: true
    name: shoponbot-production-network